# Generated by Django 4.2.7 on 2026-01-05 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisme_formation', models.CharField(default='Kompetans.fr', max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField()),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('completee', 'Complétée'), ('abandonnee', 'Abandonnée')], default='en_cours', max_length=20)),
                ('numero_session', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Habilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('categorie', models.CharField(choices=[('1', 'Basse Tension (BT)'), ('2', 'Haute Tension (HT)'), ('3', 'Mixte')], max_length=10)),
                ('niveau', models.CharField(max_length=10)),
                ('duree_validite_mois', models.IntegerField(default=36)),
                ('savoirs', models.TextField(help_text='Liste des savoirs théoriques requis')),
                ('savoirs_faire', models.TextField(help_text='Liste des savoir-faire pratiques requis')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('poste', models.CharField(max_length=150)),
                ('date_embauche', models.DateField()),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagiaires', to='habilitations_app.entreprise')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Titre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_titre', models.CharField(max_length=50, unique=True)),
                ('date_delivrance', models.DateField()),
                ('date_expiration', models.DateField()),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('delivre', 'Délivré'), ('expire', 'Expiré'), ('renouvele', 'Renouvelé')], default='attente', max_length=20)),
                ('notes_avis', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('delivre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titres_delivres', to=settings.AUTH_USER_MODEL)),
                ('formation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='habilitations_app.formation')),
                ('habilitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habilitations_app.habilitation')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titres', to='habilitations_app.stagiaire')),
            ],
            options={
                'ordering': ['-date_delivrance'],
            },
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorisations', models.TextField(default='all')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretaires', to='habilitations_app.entreprise')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RenouvellementHabilitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_renouvellement_prevue', models.DateField()),
                ('date_renouvellement_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('renouvele', 'Renouvelé'), ('expire', 'Expiré')], default='planifie', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('titre_precedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renouvellements', to='habilitations_app.titre')),
            ],
            options={
                'ordering': ['-date_renouvellement_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation_stagiaire', 'Création stagiaire'), ('creation_formation', 'Création formation'), ('validation_competence', 'Validation compétence'), ('delivrance_titre', 'Délivrance titre'), ('renouvellement', 'Renouvellement'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=30)),
                ('description', models.TextField()),
                ('objet_concerne', models.CharField(max_length=100)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habilitations_app.entreprise')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='habilitation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='habilitations_app.habilitation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='habilitations_app.stagiaire'),
        ),
        migrations.CreateModel(
            name='AvisFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.CharField(choices=[('favorable', 'Favorable'), ('favorable_condition', 'Favorable avec conditions'), ('defavorable', 'Défavorable')], max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('points_forts', models.TextField(blank=True)),
                ('points_amelioration', models.TextField(blank=True)),
                ('recommandations', models.TextField(blank=True)),
                ('formateur_nom', models.CharField(max_length=150)),
                ('date_avis', models.DateField(auto_now_add=True)),
                ('signature_formateur', models.ImageField(blank=True, upload_to='signatures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('formation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='habilitations_app.formation')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_competence', models.CharField(choices=[('savoir', 'Savoir théorique'), ('savoir_faire', 'Savoir-faire pratique')], max_length=20)),
                ('titre_competence', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=False)),
                ('commentaires_validateur', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='habilitations_app.formation')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['type_competence', 'titre_competence'],
                'unique_together': {('formation', 'titre_competence')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='formation',
            unique_together={('stagiaire', 'habilitation')},
        ),
    ]
