# Generated by Django 4.2.7 on 2026-01-05 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habilitations_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_session', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('organisme_formation', models.CharField(default='Kompetans.fr', max_length=255)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('formateur_nom', models.CharField(blank=True, max_length=150)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('nombre_places', models.IntegerField(default=12)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_creees', to=settings.AUTH_USER_MODEL)),
                ('habilitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='habilitations_app.habilitation')),
            ],
            options={
                'verbose_name': 'Session de formation',
                'verbose_name_plural': 'Sessions de formation',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='DemandeStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('poste', models.CharField(max_length=150)),
                ('date_embauche', models.DateField()),
                ('notes', models.TextField(blank=True, help_text='Informations complémentaires')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('integree', 'Intégrée à une session'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_stagiaires', to='habilitations_app.entreprise')),
                ('habilitation_demandee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='habilitations_app.habilitation')),
                ('session_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='habilitations_app.sessionformation')),
                ('stagiaire_cree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine', to='habilitations_app.stagiaire')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de stagiaire',
                'verbose_name_plural': 'Demandes de stagiaires',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.AddField(
            model_name='formation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_session', to='habilitations_app.sessionformation'),
        ),
    ]
