# Generated by Django 4.2.7 on 2026-01-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0003_profilutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='type_entreprise',
            field=models.CharField(choices=[('client', 'Client'), ('of', 'Organisme de Formation')], default='client', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('client', 'Client - Gestion des salariés'), ('of', 'Organisme de Formation - Validation des formations')], default='client', max_length=50),
        ),
        migrations.DeleteModel(
            name='Secretaire',
        ),
    ]
