# Generated by Django 4.2.7 on 2026-01-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0004_entreprise_type_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='poste',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
