# Generated by Django 4.2.7 on 2026-01-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0005_alter_stagiaire_date_embauche_alter_stagiaire_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandestagiaire',
            name='habilitation_demandee',
        ),
        migrations.AddField(
            model_name='demandestagiaire',
            name='est_renouvellement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandestagiaire',
            name='habilitations_demandees',
            field=models.ManyToManyField(related_name='demandes', to='habilitations_app.habilitation'),
        ),
        migrations.AddField(
            model_name='demandestagiaire',
            name='stagiaire_existant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_formation', to='habilitations_app.stagiaire'),
        ),
        migrations.AddField(
            model_name='demandestagiaire',
            name='titre_renouvelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_renouvellement', to='habilitations_app.titre'),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='date_embauche',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='poste',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
