# Generated by Django 4.2.7 on 2026-01-07 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habilitations_app', '0006_remove_demandestagiaire_habilitation_demandee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='organisme_formation',
            field=models.ForeignKey(default=5, help_text="L'organisme de formation qui gère ce stagiaire", limit_choices_to={'type_entreprise': 'of'}, on_delete=django.db.models.deletion.CASCADE, related_name='stagiaires_of', to='habilitations_app.entreprise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='stagiaire_existant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_stagiaires', to='habilitations_app.stagiaire'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='entreprise',
            field=models.ForeignKey(blank=True, help_text='Entreprise rattachée (NULL pour super_admin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='habilitations_app.entreprise'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin - Éditeur SaaS'), ('admin_of', 'Administrateur OF'), ('responsable_pme', 'Responsable PME'), ('stagiaire', 'Stagiaire')], default='responsable_pme', max_length=50),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='entreprise',
            field=models.ForeignKey(blank=True, help_text="L'entreprise employeur (optionnel, NULL = stagiaire indépendant)", limit_choices_to={'type_entreprise': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stagiaires', to='habilitations_app.entreprise'),
        ),
        migrations.CreateModel(
            name='DemandeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_souhaitee', models.DateField(blank=True, help_text='Date souhaitée pour la formation', null=True)),
                ('commentaire_demande', models.TextField(blank=True, help_text='Commentaire de la PME')),
                ('commentaire_reponse', models.TextField(blank=True, help_text="Réponse de l'OF")),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('demandeur', models.ForeignKey(help_text='Utilisateur ayant créé la demande', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_formation_creees', to=settings.AUTH_USER_MODEL)),
                ('entreprise_demandeuse', models.ForeignKey(help_text='La PME qui demande la formation', limit_choices_to={'type_entreprise': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_formation_emises', to='habilitations_app.entreprise')),
                ('habilitation', models.ForeignKey(help_text="Type d'habilitation demandée", on_delete=django.db.models.deletion.CASCADE, to='habilitations_app.habilitation')),
                ('organisme_formation', models.ForeignKey(help_text="L'OF qui recevra la demande", limit_choices_to={'type_entreprise': 'of'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_formation_recues', to='habilitations_app.entreprise')),
                ('session_creee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_origine', to='habilitations_app.sessionformation')),
                ('stagiaires', models.ManyToManyField(help_text='Stagiaires concernés par cette demande', related_name='demandes_formation', to='habilitations_app.stagiaire')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_formation_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de formation',
                'verbose_name_plural': 'Demandes de formation',
                'ordering': ['-date_demande'],
            },
        ),
    ]
