# Generated by Django 4.2.7 on 2026-01-07 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habilitations_app', '0007_profilutilisateur_actif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='organisme_formation',
            field=models.CharField(default='Oxalis', max_length=255),
        ),
        migrations.CreateModel(
            name='InvitationEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contact', models.EmailField(max_length=254)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('revoked', 'Révoquée'), ('expired', 'Expirée')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_acceptees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise_client', models.ForeignKey(limit_choices_to={'type_entreprise': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_recues', to='habilitations_app.entreprise')),
                ('organisme_formation', models.ForeignKey(limit_choices_to={'type_entreprise': 'of'}, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_emises', to='habilitations_app.entreprise')),
            ],
            options={
                'verbose_name': 'Invitation entreprise',
                'verbose_name_plural': 'Invitations entreprises',
                'ordering': ['-date_created'],
            },
        ),
    ]
