# Generated by ChatGPT on 2026-01-08
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('habilitations_app', '0008_alter_formation_organisme_formation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_public', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Sous-domaine slug ex: of-kompetans', max_length=80, unique=True)),
                ('domaine', models.CharField(blank=True, help_text='Domaine dédié si configuré (ex: of.example.com)', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('couleur_primaire', models.CharField(default='#2c3e50', max_length=20)),
                ('couleur_secondaire', models.CharField(default='#27ae60', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Consentement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='demande_formation', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('consent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-consent_at'],
            },
        ),
        migrations.AddField(
            model_name='entreprise',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (OF) propriétaire – obligatoire pour les PME clientes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (OF) propriétaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stagiaires', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='formation',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (OF) propriétaire', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='validationcompetence',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='titre',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titres', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='avisformation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis_formations', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='renouvellementhabilitation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renouvellements', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='formateur',
            field=models.ForeignKey(blank=True, help_text='Formateur responsable de la session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_assignees', to='auth.user'),
        ),
        migrations.AddField(
            model_name='demandeformation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_formation', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='demandeformation',
            name='consentement_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeformation',
            name='consentement_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeformation',
            name='consentement_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demandestagiaire',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_stagiaires', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='demandestagiaire',
            name='consentement_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandestagiaire',
            name='consentement_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandestagiaire',
            name='consentement_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateurs', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='consentement',
            name='demande_formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentements', to='habilitations_app.demandeformation'),
        ),
        migrations.AddField(
            model_name='consentement',
            name='stagiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentements', to='habilitations_app.stagiaire'),
        ),
        migrations.AddField(
            model_name='consentement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentements', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='consentement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['type_entreprise', 'nom'], name='entreprise_type_nom_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['tenant', 'type_entreprise'], name='entreprise_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='stagiaire',
            index=models.Index(fields=['entreprise', 'actif'], name='stagiaire_entreprise_actif_idx'),
        ),
        migrations.AddIndex(
            model_name='stagiaire',
            index=models.Index(fields=['tenant', 'actif'], name='stagiaire_tenant_actif_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['tenant', 'statut'], name='formation_tenant_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['stagiaire', 'habilitation', 'statut'], name='formation_stag_hab_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='validationcompetence',
            index=models.Index(fields=['tenant', 'type_competence'], name='validation_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='titre',
            index=models.Index(fields=['date_expiration'], name='titre_date_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='titre',
            index=models.Index(fields=['tenant', 'statut'], name='titre_tenant_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='renouvellementhabilitation',
            index=models.Index(fields=['tenant', 'statut'], name='renouv_tenant_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='renouvellementhabilitation',
            index=models.Index(fields=['date_renouvellement_prevue'], name='renouv_date_prev_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionformation',
            index=models.Index(fields=['tenant', 'statut'], name='session_tenant_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionformation',
            index=models.Index(fields=['organisme_formation', 'statut'], name='session_org_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeformation',
            index=models.Index(fields=['tenant', 'statut'], name='demande_tenant_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeformation',
            index=models.Index(fields=['entreprise_demandeuse', 'statut'], name='demande_entreprise_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeformation',
            index=models.Index(fields=['organisme_formation', 'statut'], name='demande_of_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='demandestagiaire',
            index=models.Index(fields=['tenant', 'statut'], name='demandestag_tenant_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='demandestagiaire',
            index=models.Index(fields=['entreprise', 'statut'], name='demandestag_entreprise_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='consentement',
            index=models.Index(fields=['tenant', 'scope'], name='consentement_tenant_scope_idx'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='organisme_formation',
            field=models.OneToOneField(limit_choices_to={'type_entreprise': 'of'}, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_of', to='habilitations_app.entreprise'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug', 'actif'], name='tenant_slug_actif_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['domaine'], name='tenant_domaine_idx'),
        ),
    ]
