# Generated by Django 4.2.7 on 2026-01-09 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0009_tenant_and_roles'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consentement',
            new_name='habilitatio_tenant__d1463e_idx',
            old_name='consentement_tenant_scope_idx',
        ),
        migrations.RenameIndex(
            model_name='demandeformation',
            new_name='habilitatio_tenant__da3a93_idx',
            old_name='demande_tenant_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='demandeformation',
            new_name='habilitatio_entrepr_12db5b_idx',
            old_name='demande_entreprise_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='demandeformation',
            new_name='habilitatio_organis_0b14b5_idx',
            old_name='demande_of_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='demandestagiaire',
            new_name='habilitatio_tenant__53e743_idx',
            old_name='demandestag_tenant_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='demandestagiaire',
            new_name='habilitatio_entrepr_a7f3da_idx',
            old_name='demandestag_entreprise_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='entreprise',
            new_name='habilitatio_type_en_503a84_idx',
            old_name='entreprise_type_nom_idx',
        ),
        migrations.RenameIndex(
            model_name='entreprise',
            new_name='habilitatio_tenant__f25e01_idx',
            old_name='entreprise_tenant_type_idx',
        ),
        migrations.RenameIndex(
            model_name='formation',
            new_name='habilitatio_tenant__345d27_idx',
            old_name='formation_tenant_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='formation',
            new_name='habilitatio_stagiai_efbfb0_idx',
            old_name='formation_stag_hab_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='renouvellementhabilitation',
            new_name='habilitatio_tenant__124216_idx',
            old_name='renouv_tenant_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='renouvellementhabilitation',
            new_name='habilitatio_date_re_6927d8_idx',
            old_name='renouv_date_prev_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionformation',
            new_name='habilitatio_tenant__390a8a_idx',
            old_name='session_tenant_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='sessionformation',
            new_name='habilitatio_organis_da12e5_idx',
            old_name='session_org_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='stagiaire',
            new_name='habilitatio_entrepr_18ac39_idx',
            old_name='stagiaire_entreprise_actif_idx',
        ),
        migrations.RenameIndex(
            model_name='stagiaire',
            new_name='habilitatio_tenant__7b9770_idx',
            old_name='stagiaire_tenant_actif_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='habilitatio_slug_5dcef7_idx',
            old_name='tenant_slug_actif_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='habilitatio_domaine_558408_idx',
            old_name='tenant_domaine_idx',
        ),
        migrations.RenameIndex(
            model_name='titre',
            new_name='habilitatio_date_ex_3feaaf_idx',
            old_name='titre_date_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='titre',
            new_name='habilitatio_tenant__a6671d_idx',
            old_name='titre_tenant_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='validationcompetence',
            new_name='habilitatio_tenant__438457_idx',
            old_name='validation_tenant_type_idx',
        ),
        migrations.AddField(
            model_name='demandeformation',
            name='lieu_formation',
            field=models.CharField(choices=[('sur_site', 'Sur le site du client'), ('chez_of', "Au siège de l'organisme de formation")], default='sur_site', help_text='Lieu de déroulement de la formation', max_length=20),
        ),
        migrations.AddField(
            model_name='demandeformation',
            name='type_formation',
            field=models.CharField(choices=[('intra', 'Intra-entreprise (sur votre site)'), ('inter', "Inter-entreprise (chez l'OF)")], default='intra', help_text='Type de formation : intra-entreprise ou inter-entreprise', max_length=10),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (OF) propriétaire – obligatoire pour les Clients', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entreprises', to='habilitations_app.tenant'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin - Éditeur SaaS'), ('admin_of', 'Administrateur OF'), ('secretariat', 'Secrétariat OF'), ('formateur', 'Formateur OF'), ('responsable_pme', 'Responsable PME'), ('stagiaire', 'Stagiaire')], default='responsable_pme', max_length=50),
        ),
    ]
