# Generated by Django 4.2.7 on 2026-01-10 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habilitations_app', '0010_rename_consentement_tenant_scope_idx_habilitatio_tenant__d1463e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormateurCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Certifications, expérience, etc.')),
            ],
            options={
                'verbose_name': 'Compétence formateur',
            },
        ),
        migrations.CreateModel(
            name='Specialisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duree_validite_mois', models.IntegerField(blank=True, help_text='NULL = prendre le défaut du type', null=True)),
                ('savoirs', models.TextField(blank=True, help_text='Savoirs théoriques spécifiques')),
                ('savoirs_faire', models.TextField(blank=True, help_text='Savoir-faire pratiques spécifiques')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Spécialisation',
                'ordering': ['type_formation', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TenantFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Formation proposée par OF',
            },
        ),
        migrations.CreateModel(
            name='TypeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duree_validite_mois_defaut', models.IntegerField(default=36)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Type de formation',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='demandestagiaire',
            options={'ordering': ['-date_demande'], 'verbose_name': 'Demande stagiaire indépendant', 'verbose_name_plural': 'Demandes stagiaires indépendants'},
        ),
        migrations.AlterModelOptions(
            name='habilitation',
            options={'ordering': ['code'], 'verbose_name': 'Habilitation (LEGACY)'},
        ),
        migrations.RemoveIndex(
            model_name='demandestagiaire',
            name='habilitatio_entrepr_a7f3da_idx',
        ),
        migrations.RemoveField(
            model_name='demandestagiaire',
            name='date_embauche',
        ),
        migrations.RemoveField(
            model_name='demandestagiaire',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='demandestagiaire',
            name='poste',
        ),
        migrations.AddField(
            model_name='demandestagiaire',
            name='statut_professionnel',
            field=models.CharField(blank=True, help_text='Auto-entrepreneur, Freelance, Particulier, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='habilitations_demandees',
            field=models.ManyToManyField(blank=True, related_name='demandes_independants_legacy', to='habilitations_app.habilitation'),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='session_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_independants', to='habilitations_app.sessionformation'),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='stagiaire_cree',
            field=models.ForeignKey(blank=True, help_text='Stagiaire créé à partir de cette demande (entreprise=NULL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_origine_independant', to='habilitations_app.stagiaire'),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='stagiaire_existant',
            field=models.ForeignKey(blank=True, help_text='Si stagiaire déjà dans la base', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_stagiaires', to='habilitations_app.stagiaire'),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='titre_renouvelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_renouvellement_independant', to='habilitations_app.titre'),
        ),
        migrations.AlterField(
            model_name='demandestagiaire',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_independants_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionformation',
            name='formateur',
            field=models.ForeignKey(blank=True, help_text='Formateur responsable de la session - doit maîtriser TOUTES les spécialisations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_assignees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sessionformation',
            name='habilitation',
            field=models.ForeignKey(blank=True, help_text='LEGACY - Voir type_formation et spécialisations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_legacy', to='habilitations_app.habilitation'),
        ),
        migrations.AlterField(
            model_name='titre',
            name='habilitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titres_legacy', to='habilitations_app.habilitation'),
        ),
        migrations.AlterField(
            model_name='validationcompetence',
            name='titre_competence',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='validationcompetence',
            name='type_competence',
            field=models.CharField(blank=True, choices=[('savoir', 'Savoir théorique'), ('savoir_faire', 'Savoir-faire pratique')], max_length=20),
        ),
        migrations.AddField(
            model_name='tenantformation',
            name='spécialisations',
            field=models.ManyToManyField(related_name='propositions_of', to='habilitations_app.specialisation'),
        ),
        migrations.AddField(
            model_name='tenantformation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_proposees', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='tenantformation',
            name='type_formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habilitations_app.typeformation'),
        ),
        migrations.AddField(
            model_name='specialisation',
            name='type_formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialisations', to='habilitations_app.typeformation'),
        ),
        migrations.AddField(
            model_name='formateurcompetence',
            name='formateur_profil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='habilitations_app.profilutilisateur'),
        ),
        migrations.AddField(
            model_name='formateurcompetence',
            name='specialisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formateurs', to='habilitations_app.specialisation'),
        ),
        migrations.AddField(
            model_name='demandestagiaire',
            name='spécialisations_demandees',
            field=models.ManyToManyField(blank=True, help_text='Spécialisations précises demandées', related_name='demandes_independants', to='habilitations_app.specialisation'),
        ),
        migrations.AddField(
            model_name='demandestagiaire',
            name='type_formation',
            field=models.ForeignKey(blank=True, help_text='Type de formation demandée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_independants', to='habilitations_app.typeformation'),
        ),
        migrations.AddField(
            model_name='habilitation',
            name='specialisation_liee',
            field=models.OneToOneField(blank=True, help_text='Spécialisation moderne correspondante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habilitation_legacy', to='habilitations_app.specialisation'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='spécialisations',
            field=models.ManyToManyField(blank=True, help_text='Spécialisations enseignées dans cette session', related_name='sessions', to='habilitations_app.specialisation'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='type_formation',
            field=models.ForeignKey(blank=True, help_text='Type de formation dispensée', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='habilitations_app.typeformation'),
        ),
        migrations.AddField(
            model_name='titre',
            name='specialisation',
            field=models.ForeignKey(blank=True, help_text='Spécialisation certifiée par ce titre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titres', to='habilitations_app.specialisation'),
        ),
        migrations.AddField(
            model_name='validationcompetence',
            name='specialisation',
            field=models.ForeignKey(blank=True, help_text="Spécialisation validée (remplace l'ancien système)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='habilitations_app.specialisation'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantformation',
            unique_together={('tenant', 'type_formation')},
        ),
        migrations.AlterUniqueTogether(
            name='specialisation',
            unique_together={('type_formation', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='formateurcompetence',
            unique_together={('formateur_profil', 'specialisation')},
        ),
    ]
