# Generated by Django 4.2.7 on 2026-01-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0011_formateurcompetence_specialisation_tenantformation_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='demandestagiaire',
            index=models.Index(fields=['type_formation', 'statut'], name='habilitatio_type_fo_f8d539_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionformation',
            index=models.Index(fields=['type_formation', 'statut'], name='habilitatio_type_fo_266dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='titre',
            index=models.Index(fields=['specialisation', 'statut'], name='habilitatio_special_164238_idx'),
        ),
    ]
