# Generated by Django 4.2.7 on 2026-01-11 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0012_add_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormateurAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='sessionformation',
            name='habilitatio_organis_da12e5_idx',
        ),
        migrations.RemoveField(
            model_name='sessionformation',
            name='formateur_nom',
        ),
        migrations.RemoveField(
            model_name='sessionformation',
            name='organisme_formation',
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='formateurs',
            field=models.ManyToManyField(blank=True, help_text='Formateurs responsables de la session - doivent maîtriser TOUTES les spécialisations', limit_choices_to={'role': 'formateur'}, related_name='sessions_formateur', to='habilitations_app.profilutilisateur'),
        ),
        migrations.AddField(
            model_name='formateuraffectation',
            name='entreprise',
            field=models.ForeignKey(limit_choices_to={'type_entreprise': 'of'}, on_delete=django.db.models.deletion.CASCADE, related_name='formateurs_affectes', to='habilitations_app.entreprise'),
        ),
        migrations.AddField(
            model_name='formateuraffectation',
            name='formateur',
            field=models.ForeignKey(limit_choices_to={'role': 'formateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='habilitations_app.profilutilisateur'),
        ),
        migrations.AddIndex(
            model_name='formateuraffectation',
            index=models.Index(fields=['entreprise', 'formateur', 'actif'], name='habilitatio_entrepr_6fb4ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='formateuraffectation',
            unique_together={('formateur', 'entreprise')},
        ),
    ]
