# Generated by Django 4.2.7 on 2026-01-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0013_formateuraffectation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeformation',
            options={'ordering': ['nom'], 'verbose_name': 'Type de formation'},
        ),
        migrations.RemoveField(
            model_name='typeformation',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='typeformation',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='typeformation',
            name='duree_validite_mois_defaut',
        ),
        migrations.AddField(
            model_name='typeformation',
            name='created_by_tenant',
            field=models.ForeignKey(blank=True, help_text='Si rempli, formation custom de cet OF. Si null, formation globale.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formations_custom', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='typeformation',
            name='duree_validite_mois',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
