# Generated by Django 4.2.7 on 2026-01-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0014_alter_typeformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeformation',
            name='titre_officiel',
            field=models.CharField(blank=True, help_text="Titre complet avec normes/références (ex: Préparation à l'habilitation électrique - NF C18-510)", max_length=500),
        ),
        migrations.AlterField(
            model_name='typeformation',
            name='created_by_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formations_custom', to='habilitations_app.tenant'),
        ),
    ]
