# Generated by Django 4.2.7 on 2026-01-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0015_typeformation_titre_officiel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantformation',
            options={'ordering': ['tenant', 'type_formation', 'nom_package'], 'verbose_name': 'Formation proposée par OF'},
        ),
        migrations.AlterUniqueTogether(
            name='tenantformation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tenantformation',
            name='nom_package',
            field=models.CharField(blank=True, help_text="Nom de l'offre (ex: 'Pack Basique', 'Formation Complète')", max_length=100, null=True),
        ),
    ]
