# Generated by Django 4.2.7 on 2026-01-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0016_alter_tenantformation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='cree_par_admin',
            field=models.BooleanField(default=False, help_text="Indique si l'entreprise a été créée par un admin OF"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='of_associes',
            field=models.ManyToManyField(blank=True, help_text='Organismes de Formation ayant accès à ce client', related_name='client_associes', to='habilitations_app.tenant'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='visible_par_admin',
            field=models.BooleanField(default=True, help_text="Indique si l'entreprise est visible par les admins OF"),
        ),
    ]
