# Generated by Django 4.2.7 on 2026-01-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0017_entreprise_cree_par_admin_entreprise_of_associes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeformation',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
