# Generated by Django 4.2.7 on 2026-01-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habilitations_app', '0018_alter_typeformation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilitation',
            name='specialisation_liee',
        ),
        migrations.AlterModelOptions(
            name='validationcompetence',
            options={'ordering': ['specialisation']},
        ),
        migrations.RemoveIndex(
            model_name='formation',
            name='habilitatio_stagiai_efbfb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='validationcompetence',
            name='habilitatio_tenant__438457_idx',
        ),
        migrations.AlterUniqueTogether(
            name='formation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='validationcompetence',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='demandeformation',
            name='habilitation',
        ),
        migrations.RemoveField(
            model_name='demandestagiaire',
            name='habilitations_demandees',
        ),
        migrations.RemoveField(
            model_name='sessionformation',
            name='formateur',
        ),
        migrations.RemoveField(
            model_name='sessionformation',
            name='habilitation',
        ),
        migrations.RemoveField(
            model_name='titre',
            name='habilitation',
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='entreprise',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_entreprise': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stagiaires', to='habilitations_app.entreprise'),
        ),
        migrations.AlterField(
            model_name='validationcompetence',
            name='specialisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='habilitations_app.specialisation'),
        ),
        migrations.AlterUniqueTogether(
            name='validationcompetence',
            unique_together={('formation', 'specialisation')},
        ),
        migrations.AddIndex(
            model_name='validationcompetence',
            index=models.Index(fields=['tenant', 'specialisation'], name='habilitatio_tenant__9e574f_idx'),
        ),
        migrations.RemoveField(
            model_name='formation',
            name='habilitation',
        ),
        migrations.RemoveField(
            model_name='validationcompetence',
            name='titre_competence',
        ),
        migrations.RemoveField(
            model_name='validationcompetence',
            name='type_competence',
        ),
        migrations.DeleteModel(
            name='Habilitation',
        ),
    ]
